### ISSUE TITLE
部分可见性判断

### ISSUE THREAD

**Issue by TInaWangxue** [hh23333/TSD#1]
您好，我想请问一下，您的mask generator那一部分，您使用全连接层进行分类从而划分人体部分，可见性为什么要用预测呢，这里我不太懂，训练的可见性标签又是什么呀，因为一般都是直接根据概率判断的，谢谢啦
![image](https://github.com/hh23333/TSD/assets/52588760/681a79e9-0090-4868-b772-1026d9b73599)
![image](https://github.com/hh23333/TSD/assets/52588760/81beb171-278e-4621-8e11-2313974b03d1)

**Comment by hh23333** [comment]
你好，我们想保持encoder-decoder简洁的结构，所以mask
generator只在训练中用，目的是得到噪声更小的parsing伪标签。所以测试的时候不会有mask输出，不能根据mask来判断局部可见性，所以在decoder输出token之上又加了个可见性预测的head，标签是human
parsing结果里边这部分是不是可见，有就是1，没有就是0。

TInaWangxue ***@***.***> 于2024年3月12日周二 10:20写道：
