### ISSUE TITLE
model reproduce

### ISSUE THREAD

**Issue by Guangdeng-Li** [hh23333/TSD#4]
Dear Author,

   I have read your paper in detail and am greatly interested in your research findings. At the same time, I must extend my sincere congratulations to you for the significant progress you have made in the performance of occluded person re-identification models.

   I have reviewed your publicly available code and attempted to reproduce your model. However, I regret to inform you that I have not been able to achieve similar results. Therefore, I would very much appreciate your assistance and guidance. If you could offer some suggestions on the configuration files and training steps, I would be extremely grateful.

**Comment by hh23333** [comment]
Thank you for your interest in our paper. Could you please share your current results and the log file for review?
